//API for client side of Eltex Media Manager

syntax = "proto3";

package mm.client_api;

import "mm_objects.proto";

service ConnectionService
{
  /* Establish connection with server */
  rpc Connect(ConnectRequest) returns (ConnectResponse) {}
}

service EventService
{
  rpc TonePlayed(TonePlayedEvent) returns (TonePlayedResponse) {}
  rpc AudioFilePlayed(AudioFilePlayedEvent) returns (AudioFilePlayedResponse) {}
  rpc DTMFDetected(DTMFDetectedEvent) returns (DTMFDetectedEventResponse) {}
  rpc RecordingStopped(RecordingStoppedEvent) returns (RecordingStoppedEventResponse) {}
  rpc ConfRecordingStopped(ConfRecordingStoppedEvent) returns (ConfRecordingStoppedEventResponse) {}
  rpc VolumeChanged(VolumeChangedEvent) returns (VolumeChangedEventResponse) {}
  rpc AudioSequencePlayed(AudioSequencePlayedEvent) returns (AudioSequencePlayedEventResponse) {}
  rpc RtpIncoming(RtpIncomingEvent) returns (RtpIncomingEventResponse) {}
  rpc StreamClosed(StreamClosedEvent) returns (StreamClosedEventResponse) {}
}

message ConnectRequest
{
  uint32 media_manager_id     = 1;
  string version              = 2;
  string session_id           = 3;
  string server_ip            = 4;
  uint32 server_port          = 5;
}

message ConnectResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message TonePlayedEvent
{
  uint64 channel_id               = 1;
  uint32 tonegen_id               = 2;
}

message TonePlayedResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message AudioFilePlayedEvent
{
  uint64 channel_id               = 1;
  uint32 player_id                = 2;
}

message AudioFilePlayedResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message DTMFDetectedEvent
{
  uint64 channel_id                   = 1;
  mm.objects.DTMFSignalType signal    = 2;
  mm.objects.DTMFDetectorType type    = 3;
}

message DTMFDetectedEventResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message RecordingStoppedEvent
{
  uint64 channel_id                        = 1;
  uint32 recorder_id                       = 2;
  mm.objects.PortStopReason reason         = 3;
  string recording_duration                = 4;
}

message RecordingStoppedEventResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message ConfRecordingStoppedEvent
{
  uint64 context_id                        = 1;
  uint32 recorder_id                       = 2;
  mm.objects.PortStopReason reason         = 3;
  string recording_duration                = 4;
}

message ConfRecordingStoppedEventResponse
{
  mm.objects.ReplyCode reply_code   = 1;
}

message VolumeChangedEvent
{
  uint64 channel_id               = 1;
  uint32 vol_level                = 2;
}

message VolumeChangedEventResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message AudioSequencePlayedEvent
{
  uint64 channel_id                  = 1;
  uint32 seq_id                      = 2;
}

message AudioSequencePlayedEventResponse
{
  mm.objects.ReplyCode reply_code    = 1;
}

message RtpIncomingEvent
{
  uint64 channel_id               = 1;
}

message RtpIncomingEventResponse
{
  mm.objects.ReplyCode reply_code = 1;
}

message StreamClosedEvent
{
  uint64 channel_id                    = 1;
  mm.objects.MediaType type           = 2;
  mm.objects.PortStopReason reason     = 3;
}

message StreamClosedEventResponse
{
  mm.objects.ReplyCode reply_code = 1;
}
